version: "3.7"

services:
  db-manager:
    build:
      context: .
      dockerfile: "./docker/db-manager/Dockerfile"
      target: db-dev
    container_name: portfolio-db-manager
    env_file: ./db-manager/.env
    volumes:
      - db-manager:/db
    tty: true

  db-client:
    build:
      context: .
      dockerfile: "./docker/db-client/Dockerfile"
    container_name: portfolio-db-client
    env_file: ./db-client/.env
    volumes:
      - db-manager:/db
    command: sqlite_web /db/portfolio.sqlite3 --password -H 0.0.0.0 -p 5432
    tty: true
    ports:
      - "5432:5432"

  # TODO: works-server

  nginx:
    image: nginx:1.24
    container_name: portfolio-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/log:/var/log/nginx
    restart: always
    depends_on:
      - works-server
    ports:
      - "8800:80"

volumes:
  db-manager:
