version: "3.7"

services:
  blog-server:
    build:
      context: ./
      dockerfile: "./resources/haskell/Dockerfile"
      target: blog-server-prod
    container_name: portfolio-blog-server
    volumes:
      - ./haskell/blog-server:/var/www/project
      - stack-work:/var/www/project/.stack-work
    working_dir: /var/www/project
    env_file: ./haskell/blog-server/.env
    command: portfolio
    tty: true

  ogp-server:
    build:
      context: ./
      dockerfile: "./resources/rust/Dockerfile"
      target: ogp-server-prod
    container_name: portfolio-ogp-server
    volumes:
      - ./rust/ogp_server:/var/www/project
      - target:/var/www/project/target
    working_dir: /var/www/project
    env_file: ./rust/ogp_server/.env
    command: ./script.sh
    tty: true

  node:
    build:
      context: ./
      dockerfile: "./resources/node/Dockerfile"
    container_name: portfolio-node
    volumes:
      - ./client:/var/www/project
      - node_modules:/var/www/project/node_modules
    env_file: ./client/.env
    command: npm run build
    tty: true

  nginx:
    image: nginx:1.22-alpine
    container_name: portfolio-nginx
    volumes:
      - ./resources/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./resources/nginx/log:/var/log/nginx
      - ./client/dist:/var/www/project/public
    restart: always
    depends_on:
      - blog-server
      - ogp-server
      - node
    ports:
      - "80:80"

volumes:
  stack-work:
  node_modules:
  target:
