version: "3.7"

services:
  db-manager:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/portfolio-db-manager:latest
    container_name: portfolio-db-manager
    env_file: ./db-manager/.env
    command: ./entrypoint.sh
    volumes:
      - db-manager:/db
    tty: true

  blog-server:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/portfolio-blog-server:latest
    container_name: portfolio-blog-server
    volumes:
      - ./haskell/blog-server:/var/www/project
      - db-manager:/var/www/project/db
    working_dir: /var/www/project
    env_file: ./haskell/blog-server/.env
    command: portfolio
    tty: true
    depends_on:
      - db-manager

  nginx:
    image: nginx:1.22-alpine
    container_name: portfolio-nginx
    volumes:
      - ./resources/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./resources/nginx/log:/var/log/nginx
    restart: always
    depends_on:
      - blog-server
    ports:
      - "80:80"

volumes:
  stack-work:
  db-manager:
