version: "3.7"

services:
  db-manager:
    build:
      context: ./db-manager
      dockerfile: "./resources/db-manager/Dockerfile"
      target: db-dev
    container_name: portfolio-db-manager
    env_file: ./db-manager/.env
    volumes:
      - db-manager:/db
    tty: true

  blog-server:
    build:
      context: ./haskell/blog-server
      dockerfile: "./resources/haskell/Dockerfile"
      target: blog-server-dev
    container_name: portfolio-blog-server
    volumes:
      - ./haskell/blog-server:/var/www/project
      - stack-work:/var/www/project/.stack-work
      - db-manager:/var/www/project/db
    working_dir: /var/www/project
    env_file: ./haskell/blog-server/.env
    command: ghcid --command "stack ghci portfolio:exe:portfolio-exe" --test "Main.main"
    tty: true
    depends_on:
      - db-manager

  node:
    build:
      context: ./client
      dockerfile: "./resources/node/Dockerfile"
    container_name: portfolio-node
    volumes:
      - ./client:/var/www/project
      - node_modules:/var/www/project/node_modules
    env_file: ./client/.env
    command: npm run dev
    tty: true

  nginx:
    image: nginx:1.22-alpine
    container_name: portfolio-nginx
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/nginx/log:/var/log/nginx
      - ./client/dist:/var/www/project/public
    restart: always
    depends_on:
      - blog-server
      - node
    ports:
      - "8800:80"

volumes:
  stack-work:
  node_modules:
  db-manager:
