version: "3.7"

services:
  db-manager:
    build:
      context: .
      dockerfile: "./resources/db-manager/Dockerfile"
      target: db-dev
    container_name: portfolio-db-manager
    env_file: ./db-manager/.env
    volumes:
      - db-manager:/db
    command: sqlite_web ./portfolio.sqlite3 --password -H 0.0.0.0 -p 5432
    tty: true
    ports:
      - "5432:5432"

  blog-server:
    build:
      context: .
      dockerfile: "./resources/haskell/Dockerfile"
      target: blog-server-dev
    container_name: portfolio-blog-server
    volumes:
      - ./haskell/blog-server:/var/www/project
      - stack-work:/var/www/project/.stack-work
      - db-manager:/var/www/project/db
    working_dir: /var/www/project
    env_file: ./haskell/blog-server/.env
    command: ghcid --command "stack ghci portfolio:exe:portfolio-exe" --test "Main.main"
    tty: true
    depends_on:
      - db-manager

  nginx:
    image: nginx:1.22-alpine
    container_name: portfolio-nginx
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/nginx/log:/var/log/nginx
    restart: always
    depends_on:
      - blog-server
    ports:
      - "8800:80"

volumes:
  stack-work:
  db-manager:
