version: "3"

services:
  node:
    build:
      context: ./
      dockerfile: "./resources/node/Dockerfile"
    container_name: portfolio-node
    volumes:
      - ./client:/var/www/project
      - node_modules:/var/www/project/node_modules
    env_file: ./client/.env
    command: npm run start
    tty: true

  nginx:
    image: nginx:1.22-alpine
    container_name: portfolio-nginx
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/nginx/log:/var/log/nginx
      - ./client/dist:/var/www/project/public
    restart: always
    depends_on:
      - node
    ports:
      - "7000:80"

volumes:
  node_modules:
